#!/usr/bin/env python3
"""Run a real unittest suite and write a Markdown experiment report."""

from __future__ import annotations

import argparse
import datetime as dt
import io
import os
import platform
import re
import sys
import unittest
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--start-dir", default="tests")
    parser.add_argument("--pattern", default="test*.py")
    parser.add_argument("--top-level-dir", default=None)
    parser.add_argument("--experiment", default=os.getenv("TAO_EXPERIMENT_NUMBER", "001"))
    parser.add_argument("--report-dir", default=os.getenv("TAO_REPORT_DIR", "docs"))
    return parser.parse_args()


def flatten(items):
    for item in items:
        if isinstance(item, (list, tuple)):
            yield from flatten(item)
        else:
            yield item


def main() -> int:
    args = parse_args()
    if not re.fullmatch(r"[A-Za-z0-9_-]+", args.experiment):
        raise SystemExit("experiment must contain only letters, numbers, '_' or '-'")

    loader = unittest.TestLoader()
    suite = loader.discover(
        start_dir=args.start_dir,
        pattern=args.pattern,
        top_level_dir=args.top_level_dir,
    )
    output = io.StringIO()
    result = unittest.TextTestRunner(stream=output, verbosity=2).run(suite)
    report_dir = Path(args.report_dir)
    report_dir.mkdir(parents=True, exist_ok=True)
    report_path = report_dir / f"experiment_{args.experiment}.md"
    timestamp = dt.datetime.now(dt.timezone.utc).isoformat()
    skipped = list(getattr(result, "skipped", []))
    failures = list(result.failures)
    errors = list(result.errors)
    status = "PASSED" if result.wasSuccessful() else "FAILED"
    lines = [
        f"# Experiment {args.experiment}",
        "",
        f"- Status: **{status}**",
        f"- Started/report time (UTC): `{timestamp}`",
        f"- Host: `{platform.node()}`",
        f"- Python: `{platform.python_version()}`",
        f"- Test scope: `{args.start_dir}` / `{args.pattern}`",
        f"- TAO URL: `{os.getenv('TAO_BASE_URL', 'not set')}`",
        f"- Tests executed: `{result.testsRun}`",
        f"- Failures: `{len(failures)}`",
        f"- Errors: `{len(errors)}`",
        f"- Skipped: `{len(skipped)}`",
        "",
        "## Result",
        "",
        "```text",
        output.getvalue().rstrip(),
        "```",
        "",
        "## Interpretation",
        "",
        "This report was generated by the real unittest runner. The test suite "
        "does not use mocked HTTP responses.",
    ]
    if failures or errors:
        lines.extend(["", "## Issues", "", "The run requires investigation before approval."])
    elif skipped:
        lines.extend(["", "## Skips", "", "Some tests were intentionally disabled by environment gates."])
    else:
        lines.extend(["", "## Conclusion", "", "All tests in this scope passed."])
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"report={report_path}")
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    sys.exit(main())
